version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.0.0
      
    working_directory: ~/til

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # lint
      - run: yarn lint


